name: inference-api
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # - python=3.8
  - python=3.10
  - git-lfs
  # main
  - requests
  - pydantic
  - fastapi
  - pandas
  - numpy
  - pytest
  - environs
  - loguru
  # main, pytorch and llm things
  - protobuf
  - pytorch:pytorch
  # - conda-forge:transformers
  # - sentencepiece
  # - sentence-transformers
  # other python utils
  - black
  - flake8
  - isort
  - pip
  - pip:
      - transformers
      - sentencepiece
      - sentence-transformers
