name: inference-api
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - git-lfs
  # main
  - requests
  - pydantic
  - fastapi
  - pandas
  - numpy
  - pytest
  - environs
  - protobuf
  - pytorch:pytorch
  - conda-forge:transformers
  - sentence-transformers
  # other python utils
  - black
  - flake8
  - pip
